import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import { notifyOwner } from "./_core/notification";
import { createImage, getImages, getImageById, updateImage, deleteImage } from "./db";

import { storagePut } from "./storage";
import { z } from "zod";



export const appRouter = router({
  // if you need to use socket.io, read and register route in server/_core/index.ts, all api should start with '/api/' so that the gateway can route correctly
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return {
        success: true,
      } as const;
    }),
  }),

  // Analytics report generation
  analytics: router({
    generateWeeklyReport: publicProcedure.mutation(async () => {
      const oneWeekAgo = new Date();
      oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
      
      // Contact functionality has been removed
      const stats = { total: 0, byStatus: {} };
      const submissions: any[] = [];
      
      // Format the report
      const reportDate = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
      
      const weekStart = oneWeekAgo.toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      
      const weekEnd = new Date().toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
      });

      let reportContent = `
# ALFA NERO Weekly Analytics Report

**Report Generated:** ${reportDate}
**Period:** ${weekStart} - ${weekEnd}

---

## Contact Form Submissions

**Total Inquiries This Week:** ${stats.total}

### Submission Status Breakdown
`;

      if (stats.total > 0) {
        for (const [status, count] of Object.entries(stats.byStatus)) {
          reportContent += `- **${status.charAt(0).toUpperCase() + status.slice(1)}:** ${count}\n`;
        }

        reportContent += `\n### Inquiry Details\n\n`;
        
        for (const sub of submissions) {
          const submittedAt = sub.createdAt.toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          });
          reportContent += `**${sub.name}** (${sub.email})\n`;
          reportContent += `*Submitted: ${submittedAt}*\n`;
          reportContent += `> ${sub.message.substring(0, 150)}${sub.message.length > 150 ? '...' : ''}\n\n`;
        }
      } else {
        reportContent += `\n*No contact form submissions this week.*\n`;
      }

      reportContent += `
---

## Recommendations

${stats.total === 0 ? '- Consider promoting the website through yacht publications and social media to increase inquiries.' : ''}
- Review the Dashboard in the Management UI for detailed visitor analytics.

---
*This report was automatically generated by the ALFA NERO website.*
      `.trim();

      // Send the report via notification
      const sent = await notifyOwner({
        title: `ALFA NERO Weekly Report: ${stats.total} Inquiries (${weekStart} - ${weekEnd})`,
        content: reportContent,
      });

      return {
        success: sent,
        stats,
        reportGenerated: new Date().toISOString(),
      };
    }),
  }),

  // Image Library Management (Admin only)
  images: router({
    // List images with optional category filter
    list: protectedProcedure
      .input(z.object({
        category: z.string().optional(),
        limit: z.number().min(1).max(100).default(50),
        offset: z.number().min(0).default(0),
      }))
      .query(async ({ input }) => {
        return getImages(input.category, input.limit, input.offset);
      }),

    // Get single image by ID
    get: protectedProcedure
      .input(z.object({ id: z.number() }))
      .query(async ({ input }) => {
        return getImageById(input.id);
      }),

    // Upload a new image
    upload: protectedProcedure
      .input(z.object({
        filename: z.string(),
        mimeType: z.string(),
        fileSize: z.number(),
        base64Data: z.string(),
        category: z.enum([
          "master-cabin",
          "guest-cabins",
          "interior",
          "exterior",
          "deck-spaces",
          "wellness",
          "lifestyle",
          "aerial",
          "technical",
          "art",
          "uncategorized"
        ]).default("uncategorized"),
        title: z.string().optional(),
        description: z.string().optional(),
        altText: z.string().optional(),
        width: z.number().optional(),
        height: z.number().optional(),
      }))
      .mutation(async ({ input, ctx }) => {
        // Generate unique file key
        const timestamp = Date.now();
        const randomSuffix = Math.random().toString(36).substring(2, 8);
        const extension = input.filename.split('.').pop() || 'jpg';
        const fileKey = `images/${input.category}/${timestamp}-${randomSuffix}.${extension}`;

        // Convert base64 to buffer
        const buffer = Buffer.from(input.base64Data, 'base64');

        // Upload to S3
        const { url } = await storagePut(fileKey, buffer, input.mimeType);

        // Save to database
        const imageId = await createImage({
          fileKey,
          url,
          filename: input.filename,
          mimeType: input.mimeType,
          fileSize: input.fileSize,
          category: input.category,
          title: input.title || null,
          description: input.description || null,
          altText: input.altText || null,
          width: input.width || null,
          height: input.height || null,
          uploadedBy: ctx.user?.id || null,
        });

        return {
          success: true,
          id: imageId,
          url,
          fileKey,
        };
      }),

    // Update image metadata
    update: protectedProcedure
      .input(z.object({
        id: z.number(),
        title: z.string().optional(),
        description: z.string().optional(),
        altText: z.string().optional(),
        category: z.enum([
          "master-cabin",
          "guest-cabins",
          "interior",
          "exterior",
          "deck-spaces",
          "wellness",
          "lifestyle",
          "aerial",
          "technical",
          "art",
          "uncategorized"
        ]).optional(),
      }))
      .mutation(async ({ input }) => {
        const { id, ...updates } = input;
        const success = await updateImage(id, updates);
        return { success };
      }),

    // Delete an image
    delete: protectedProcedure
      .input(z.object({ id: z.number() }))
      .mutation(async ({ input }) => {
        const success = await deleteImage(input.id);
        return { success };
      }),

    // Get available categories
    categories: publicProcedure.query(() => {
      return [
        { value: "master-cabin", label: "Master Cabin" },
        { value: "guest-cabins", label: "Guest Cabins" },
        { value: "interior", label: "Interior" },
        { value: "exterior", label: "Exterior" },
        { value: "deck-spaces", label: "Deck Spaces" },
        { value: "wellness", label: "Wellness" },
        { value: "lifestyle", label: "Lifestyle" },
        { value: "aerial", label: "Aerial" },
        { value: "technical", label: "Technical" },
        { value: "art", label: "Art" },
        { value: "uncategorized", label: "Uncategorized" },
      ];
    }),
  }),

  // Brochure Download with Email Gateway
  brochure: router({
    captureLead: publicProcedure
      .input(z.object({
        email: z.string().email(),
        name: z.string().min(1),
      }))
      .mutation(async ({ input }) => {
        // Notify owner about new brochure download lead
        await notifyOwner({
          title: `New Brochure Download: ${input.name}`,
          content: `**Name:** ${input.name}\n**Email:** ${input.email}\n\nA visitor has requested the ALFA NERO brochure.`,
        });

        // Return brochure URL (placeholder - replace with actual brochure PDF URL)
        return {
          success: true,
          brochureUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663300921591/cwAqWBhmnJWJrnNP.pdf",
        };
      }),
  }),
});

export type AppRouter = typeof appRouter;
